/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./styles/**/*.css",
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        aera: {
          bg: "#FFFDF8",
          ink: "#3D2417",
          muted: "#74665A",
          accent: "#A7622A",
          accentHover: "#8A4F1D",
          cream: "#FFFDF8",
          champagne: "#F8EEE3",
          bronze: "#9b591d",
          bronzeDark: "#74370f",
          gold: "#d4a464",
        },
        admin: {
          canvas: "var(--admin-canvas)",
          surface: "var(--admin-surface)",
          "surface-muted": "var(--admin-surface-muted)",
          "surface-hover": "var(--admin-surface-hover)",
          "surface-raised": "var(--admin-surface-raised)",
          "sidebar-bg": "var(--admin-sidebar-bg)",
          ink: "var(--admin-ink)",
          "ink-secondary": "var(--admin-ink-secondary)",
          muted: "var(--admin-muted)",
          placeholder: "var(--admin-placeholder)",
          accent: "var(--admin-accent)",
          "accent-hover": "var(--admin-accent-hover)",
          "accent-soft": "var(--admin-accent-soft)",
          border: "var(--admin-border)",
          "border-strong": "var(--admin-border-strong)",
          "border-muted": "var(--admin-border-muted)",
          success: "var(--admin-success)",
          "success-soft": "var(--admin-success-soft)",
          warning: "var(--admin-warning)",
          "warning-soft": "var(--admin-warning-soft)",
          danger: "var(--admin-danger)",
          "danger-soft": "var(--admin-danger-soft)",
          info: "var(--admin-info)",
          "info-soft": "var(--admin-info-soft)",
          neutral: "var(--admin-neutral)",
          "neutral-soft": "var(--admin-neutral-soft)",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        heading: ["var(--font-playfair)", "serif"],
      },
      borderRadius: {
        "admin-sm": "var(--admin-radius-sm)",
        "admin-md": "var(--admin-radius-md)",
        "admin-lg": "var(--admin-radius-lg)",
        "admin-xl": "var(--admin-radius-xl)",
      },
      boxShadow: {
        luxury: "0 18px 50px rgba(77, 43, 20, 0.08)",
        "admin-sm": "var(--admin-shadow-sm)",
        "admin-md": "var(--admin-shadow-md)",
        "admin-lg": "var(--admin-shadow-lg)",
      },
    },
  },
  plugins: [],
};
